name: Deploy Helm Chart to GKE

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-helm:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate with GKE
      run: |
        set -e
        gcloud container clusters get-credentials $CLUSTER_NAME --region $REGION --project $PROJECT_ID

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: true

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform Changes
      run: |
        set -e
        terraform plan \
          -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var="region=${{ secrets.GCP_REGION }}" \
          -var="cluster_name=${{ secrets.GKE_CLUSTER_NAME }}"

    - name: Apply Terraform Changes
      run: |
        set -e
        terraform apply -auto-approve \
          -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var="region=${{ secrets.GCP_REGION }}" \
          -var="cluster_name=${{ secrets.GKE_CLUSTER_NAME }}"

    - name: Verify Deployment
      run: |
        set -e
        kubectl get pods -n default